/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jif_runtime_Runtime */

#ifndef _Included_jif_runtime_Runtime
#define _Included_jif_runtime_Runtime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jif_runtime_Runtime
 * Method:    currentUserImpl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jif_runtime_Runtime_currentUserImpl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
